global:
  resolve_timeout: 5m
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${SMTP_FROM}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASS}'
  smtp_require_tls: ${SMTP_REQUIRE_TLS}

route:
  receiver: email-default
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - matchers:
        - severity="critical"
      receiver: email-critical
    - matchers:
        - severity="warning"
      receiver: email-warning

receivers:
  - name: email-default
    email_configs:
      - to: '${ALERT_EMAIL_TO}'
        send_resolved: true

  - name: email-warning
    email_configs:
      - to: '${ALERT_EMAIL_TO}'
        send_resolved: true

  - name: email-critical
    email_configs:
      - to: '${ALERT_EMAIL_CRITICAL_TO}'
        send_resolved: true
