services:
  pgadmin:
    image: dpage/pgadmin4:9.4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=30
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - monitoring
      - traefik-global
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-global'
      - 'traefik.http.routers.${APP_SLUG:-staging}-pgadmin.rule=Host(`${PGADMIN_DOMAIN}`)'
      - 'traefik.http.routers.${APP_SLUG:-staging}-pgadmin.entrypoints=websecure'
      - 'traefik.http.routers.${APP_SLUG:-staging}-pgadmin.tls=true'
      - 'traefik.http.routers.${APP_SLUG:-staging}-pgadmin.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.${APP_SLUG:-staging}-pgadmin.priority=16'
      - 'traefik.http.services.${APP_SLUG:-staging}-pgadmin.loadbalancer.server.port=80'

networks:
  monitoring:
    driver: bridge
  traefik-global:
    external: true

volumes:
  pgadmin_data:
    driver: local
