<?php

return [
    'field_map_tables' => [
        'products' => [
            'label' => 'Produtos',
            'columns' => [
                'tenant_id',
                'user_id',
                'image_id',
                'category_id',
                'client_id',
                'name',
                'slug',
                'ean',
                'codigo_erp',
                'stackable',
                'perishable',
                'flammable',
                'hangable',
                'no_sales',
                'no_purchases',
                'description',
                'sales_status',
                'sales_purchases',
                'status',
                'sync_source',
                'resolution_status',
                'resolution_details',
                'sync_at',
                'url',
                'type',
                'reference',
                'fragrance',
                'flavor',
                'color',
                'brand',
                'subbrand',
                'packaging_type',
                'packaging_size',
                'measurement_unit',
                'packaging_content',
                'unit_measure',
                'auxiliary_description',
                'additional_information',
                'sortiment_attribute',
                'width',
                'height',
                'depth',
                'weight',
                'unit',
                'has_dimensions',
                'dimension_status',
                'current_stock',
                'last_purchase_date',
            ],
        ],
        'sales' => [
            'label' => 'Vendas',
            'columns' => [
                'tenant_id',
                'store_id',
                'product_id',
                'ean',
                'codigo_erp',
                'acquisition_cost',
                'sale_price',
                'total_profit_margin',
                'sale_date',
                'promotion',
                'total_sale_quantity',
                'total_sale_value',
                'margem_contribuicao',
                'extra_data',
            ],
        ],
        'stores' => [
            'label' => 'Lojas',
            'columns' => [
                'tenant_id',
                'user_id',
                'name',
                'document',
                'slug',
                'code',
                'phone',
                'email',
                'status',
                'description',
                'map_image_path',
                'map_regions',
            ],
        ],
    ],

    'providers' => [
        'sysmo' => [
            'requests' => [
                'method' => 'POST',
                'payload' => 'body',
                'page_field' => 'pagina',
                'page_value_type' => 'string',
                'page_size_field' => 'tamanho_pagina',
                'page_size_payload' => 'body',
                'min_page_size' => 100,
                'max_page_size' => 5000,
                'store_document_field' => 'empresa',
                'products' => [
                    'fallback_path' => '/hubprodutos.listar_produtos',
                    'default_page_size' => 500,
                    'date_fields' => [
                        'changed_since' => 'data_ultima_alteracao',
                    ],
                ],
                'sales' => [
                    'fallback_path' => '/hubvendas.vendas_produtos',
                    'date_fields' => [
                        'start' => 'data_inicial',
                        'end' => 'data_final',
                    ],
                    'dispatch_by_day' => true,
                ],
            ],
            'response' => [
                'items_path' => 'dados',
                'pagination' => [
                    'current_page_path' => 'pagina',
                    'last_page_path' => 'total_paginas',
                ],
            ],
        ],

        'gescooper' => [
            'requests' => [
                'method' => 'GET',
                'payload' => 'query',
                'store_document_field' => 'empresa',
                'page_field' => 'pagina',
                'page_value_type' => 'integer',
                'page_size_field' => 'registros_por_pagina',
                'page_size_payload' => 'query',
                'default_page_size' => 200,
                'min_page_size' => 50,
                'max_page_size' => 500,
                'fixed_query' => [
                    'api-version' => '1.0',
                ],
                'products' => [
                    'fallback_path' => '/Produtos/Produtos',
                    'date_fields' => [
                        'created_from' => 'data_cadastro_de',
                        'created_to' => 'data_cadastro_ate',
                    ],
                ],
                'sales' => [
                    'fallback_path' => '',
                    'skip_statuses' => [404],
                ],
            ],
            'response' => [
                'items_path' => 'data',
                'pagination' => [
                    'current_page_path' => 'pagination.current_page',
                    'per_page_path' => 'pagination.per_page',
                    'total_path' => 'pagination.total',
                    'last_page_path' => 'pagination.last_page',
                ],
            ],
        ],
    ],
];
