<script setup lang="ts">
import { router, usePage } from '@inertiajs/vue3';
import {  RefreshCw, Sparkles, X } from 'lucide-vue-next';
import { computed, onMounted, ref, watch } from 'vue';
import { toast } from 'vue-sonner';
import { reorderGondola, redistributeGondola, regenerateAuto } from '@/actions/Callcocam/LaravelRaptorPlannerate/Http/Controllers/Generation/AutoPlanogramController';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { useT } from '@/composables/useT';
import type { Gondola } from '../../../types/planogram';
import CategoryConfigPanel from './CategoryConfigPanel.vue';
import ReoptimizationCadenceCard from './ReoptimizationCadenceCard.vue';

interface Props {
    open: boolean;
    gondola: Gondola;
}

interface Emits {
    (e: 'close'): void;
    (e: 'reload'): void;
}

interface AllocationEntry {
    product_id: string;
    product_name: string;
    category_name: string | null;
    abc_class: 'A' | 'B' | 'C' | null;
    is_mandatory: boolean;
    facings: number;
    facings_expanded: boolean;
    zone: 'hot' | 'cold' | 'neutral';
    role: string | null;
    has_target_stock: boolean;
}

interface RejectedEntry {
    product_id: string;
    product_name: string;
    category_name: string | null;
    abc_class: 'A' | 'B' | 'C' | null;
    motivo: string;
    motivo_label: string;
}

interface StoredReport {
    gondola_id: string;
    generated_at: string;
    posicionados: number;
    total_produtos: number;
    rejeitados_espaco: number;
    rejeitados_altura: number;
    rejeitados_sem_dimensao: number;
    taxa_cobertura: number;
    score_type: string | null;
    allocated: AllocationEntry[];
    rejected: RejectedEntry[];
}

const props = defineProps<Props>();

defineEmits<Emits>();
const { t } = useT();
const page = usePage();

const STORAGE_KEY = (id: string) => `plannerate_gen_report_${id}`;

const modeLabel: Record<string, string> = {
    template: 'Template',
    automatic: 'Automático',
    manual: 'Manual',
};

const modeVariant: Record<string, 'default' | 'secondary' | 'outline'> = {
    template: 'default',
    automatic: 'secondary',
    manual: 'outline',
};

const currentMode = props.gondola.generation_mode ?? 'manual';
const isReordering = ref(false);
const isRedistributing = ref(false);
const isPromoting = ref(false);
const isRegeneratingAuto = ref(false);

/** True quando o template vinculado à gôndola foi gerado pelo modo automático */
const isAutoGeneratedTemplate = computed(
    () => props.gondola.template_origin === 'auto',
);

/** URL de promoção do template: POST /planogram-templates/{id}/promote */
function promoteUrl(templateId: string): string {
    return `/planogram-templates/${templateId}/promote`;
}

/** Relatório persistido em localStorage — sobrevive a navegações */
const storedReport = ref<StoredReport | null>(null);

function loadStoredReport(): void {
    try {
        const raw = localStorage.getItem(STORAGE_KEY(props.gondola.id));
        storedReport.value = raw ? (JSON.parse(raw) as StoredReport) : null;
    } catch {
        storedReport.value = null;
    }
}

function saveReport(cr: any): void {
    const report: StoredReport = {
        gondola_id: props.gondola.id,
        generated_at: new Date().toISOString(),
        posicionados: cr.posicionados ?? 0,
        total_produtos: cr.total_produtos ?? 0,
        rejeitados_espaco: cr.rejeitados_espaco ?? 0,
        rejeitados_altura: cr.rejeitados_altura ?? 0,
        rejeitados_sem_dimensao: cr.rejeitados_sem_dimensao ?? 0,
        taxa_cobertura: cr.taxa_cobertura ?? 0,
        score_type: cr.score_type ?? null,
        allocated: cr.explanation_report?.allocated ?? [],
        rejected: cr.explanation_report?.rejected ?? [],
    };

    try {
        localStorage.setItem(STORAGE_KEY(props.gondola.id), JSON.stringify(report));
    } catch { /* quota exceeded — ignora */ }

    storedReport.value = report;
}

/** Quando o flash traz um novo capacity_report, persiste no localStorage */
watch(
    () => (page.props.flash as any)?.capacity_report,
    (cr) => {
 if (cr) {
saveReport(cr);
} 
},
    { immediate: true },
);

onMounted(loadStoredReport);

/** Métricas derivadas do relatório armazenado */
const abcStats = computed(() => {
    const list = storedReport.value?.allocated ?? [];
    const total = list.length;
    const a = list.filter((e) => e.abc_class === 'A').length;
    const b = list.filter((e) => e.abc_class === 'B').length;
    const c = list.filter((e) => e.abc_class === 'C').length;
    const sem = list.filter((e) => e.abc_class === null).length;

    return { total, a, b, c, sem };
});

const zoneStats = computed(() => {
    const list = storedReport.value?.allocated ?? [];
    const hot = list.filter((e) => e.zone === 'hot').length;
    const cold = list.filter((e) => e.zone === 'cold').length;
    const neutral = list.filter((e) => e.zone === 'neutral').length;

    return { hot, cold, neutral };
});

function barWidth(value: number, total: number): string {
    if (total === 0) {
return '0%';
}

    return `${Math.round((value / total) * 100)}%`;
}

function coverageColor(pct: number): string {
    if (pct >= 0.8) {
return 'text-emerald-600 dark:text-emerald-400';
}

    if (pct >= 0.5) {
return 'text-yellow-600 dark:text-yellow-400';
}

    return 'text-red-600 dark:text-red-400';
}

function formattedDate(iso: string): string {
    try {
        return new Date(iso).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short' });
    } catch {
        return iso;
    }
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars -- card "Reordenar" parado, template comentado abaixo
function handleReorder() {
    isReordering.value = true;
    router.post(reorderGondola.url(props.gondola.id), {}, {
        preserveScroll: true,
        only: ['record'],
        onSuccess: () => toast.success(t('plannerate.sidebar.generation.reorder.success')),
        onError: () => toast.error(t('plannerate.sidebar.generation.reorder.error')),
        onFinish: () => {
 isReordering.value = false; 
},
    });
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars -- card "Redistribuir" parado, template comentado abaixo
function handleRedistribute() {
    isRedistributing.value = true;
    router.post(redistributeGondola.url(props.gondola.id), {}, {
        preserveScroll: true,
        only: ['record'],
        onSuccess: () => toast.success(t('plannerate.sidebar.generation.redistribute.success')),
        onError: () => toast.error(t('plannerate.sidebar.generation.redistribute.error')),
        onFinish: () => {
 isRedistributing.value = false; 
},
    });
}

function handlePromote() {
    if (!props.gondola.template_id) {
        return;
    }

    isPromoting.value = true;
    router.post(promoteUrl(props.gondola.template_id), {}, {
        preserveScroll: true,
        preserveState: false, 
        onSuccess: () => toast.success(t('plannerate.sidebar.generation.auto_generated.promote_success')),
        onError: () => toast.error(t('plannerate.sidebar.generation.auto_generated.promote_error')),
        onFinish: () => {
 isPromoting.value = false; 
},
    });
}

function handleRegenerateAuto() {
    isRegeneratingAuto.value = true;
    router.post(regenerateAuto.url(props.gondola.id), {}, {
        preserveScroll: true,
        only: ['record'],
        onSuccess: () => toast.success(t('plannerate.sidebar.generation.auto_generated.regenerate_auto_success')),
        onError: () => toast.error(t('plannerate.sidebar.generation.auto_generated.regenerate_auto_error')),
        onFinish: () => {
 isRegeneratingAuto.value = false; 
},
    });
}
</script>

<template>
    <Transition
        enter-active-class="transition-transform duration-300 ease-out"
        enter-from-class="-translate-x-full"
        enter-to-class="translate-x-0"
        leave-active-class="transition-transform duration-300 ease-in"
        leave-from-class="translate-x-0"
        leave-to-class="-translate-x-full"
    >
        <div
            v-if="open"
            class="relative z-20 flex h-full w-full sm:w-80 2xl:w-96 flex-col border-r border-border bg-background"
        >
            <!-- Header -->
            <div class="flex items-center justify-between border-b border-border px-4 py-3">
                <div class="flex items-center gap-2">
                    <span class="text-sm font-medium">{{ t('plannerate.sidebar.generation.title') }}</span>
                    <Badge :variant="modeVariant[currentMode] ?? 'outline'">
                        {{ modeLabel[currentMode] ?? currentMode }}
                    </Badge>
                </div>
                <Button variant="ghost" size="icon" class="size-7 shrink-0" @click="$emit('close')" type="button">
                    <X class="size-4" />
                </Button>
            </div>

            <!-- Template info -->
            <div v-if="gondola.template_id" class="border-b border-border bg-muted/30 px-4 py-2">
                <p class="text-xs text-muted-foreground">{{ t('plannerate.sidebar.generation.template_in_use') }}</p>
                <p class="mt-0.5 text-xs font-medium text-foreground">{{ gondola.template_name ?? gondola.template_id }}</p>
            </div>

            <!-- Content -->
            <div class="flex flex-1 flex-col gap-3 overflow-y-auto p-4">

                <!-- Card: Template gerado automaticamente -->
                <div
                    v-if="isAutoGeneratedTemplate && gondola.template_id"
                    class="rounded-lg border border-violet-200 bg-violet-50 p-4 shadow-sm dark:border-violet-800 dark:bg-violet-950"
                >
                    <div class="flex items-start gap-3">
                        <div class="mt-0.5 rounded-md bg-violet-500/10 p-2">
                            <Sparkles class="size-4 text-violet-600 dark:text-violet-400" />
                        </div>
                        <div class="flex-1">
                            <p class="text-sm font-medium text-violet-900 dark:text-violet-100">
                                {{ t('plannerate.sidebar.generation.auto_generated.title') }}
                            </p>
                            <p class="mt-1 text-xs text-violet-700 dark:text-violet-300">
                                {{ t('plannerate.sidebar.generation.auto_generated.description') }}
                            </p>
                            <div class="mt-3 flex flex-col gap-2">
                                <Button
                                    variant="default"
                                    size="sm"
                                    class="w-full bg-violet-600 hover:bg-violet-700 text-white"
                                    :disabled="isPromoting"
                                    @click="handlePromote"
                                    type="button"
                                >
                                    <span v-if="isPromoting" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                    <Sparkles v-else class="mr-2 size-3.5" />
                                    {{ t('plannerate.sidebar.generation.auto_generated.promote') }}
                                </Button>
                                <Button
                                    variant="outline"
                                    size="sm"
                                    class="w-full"
                                    :disabled="isRegeneratingAuto"
                                    @click="handleRegenerateAuto"
                                    type="button"
                                >
                                    <span v-if="isRegeneratingAuto" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                    <RefreshCw v-else class="mr-2 size-3.5" />
                                    {{ t('plannerate.sidebar.generation.auto_generated.regenerate_auto') }}
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>

                <Separator v-if="isAutoGeneratedTemplate && gondola.template_id" />

                <!-- Configurações por categoria -->
                <CategoryConfigPanel :gondola="gondola" />

                <Separator />

                <!-- Reotimização contínua -->
                <ReoptimizationCadenceCard :gondola="gondola" />

                <!-- Relatório da última geração -->
                <template v-if="storedReport">
                    <Separator />

                    <div class="rounded-lg border border-border bg-muted/20 p-3">
                        <!-- Cabeçalho do relatório -->
                        <div class="mb-3 flex items-center justify-between">
                            <p class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                                Resultado da Geração
                            </p>
                            <span class="text-[10px] text-muted-foreground">
                                {{ formattedDate(storedReport.generated_at) }}
                            </span>
                        </div>

                        <!-- Métricas principais -->
                        <div class="mb-3 grid grid-cols-2 gap-2">
                            <div class="rounded bg-emerald-50 px-2 py-1.5 dark:bg-emerald-950/30">
                                <p class="text-[10px] uppercase text-emerald-600 dark:text-emerald-400">Posicionados</p>
                                <p class="text-lg font-bold text-emerald-700 dark:text-emerald-300">
                                    {{ storedReport.posicionados }}
                                    <span class="text-xs font-normal text-emerald-500">/{{ storedReport.total_produtos }}</span>
                                </p>
                            </div>
                            <div class="rounded bg-muted px-2 py-1.5">
                                <p class="text-[10px] uppercase text-muted-foreground">Cobertura</p>
                                <p class="text-lg font-bold" :class="coverageColor(storedReport.taxa_cobertura)">
                                    {{ Math.round(storedReport.taxa_cobertura * 100) }}%
                                </p>
                            </div>
                            <div v-if="storedReport.rejeitados_espaco > 0" class="rounded bg-amber-50 px-2 py-1.5 dark:bg-amber-950/30">
                                <p class="text-[10px] uppercase text-amber-600 dark:text-amber-400">Sem espaço</p>
                                <p class="text-lg font-bold text-amber-700 dark:text-amber-300">{{ storedReport.rejeitados_espaco }}</p>
                            </div>
                            <div v-if="storedReport.rejeitados_sem_dimensao > 0" class="rounded bg-purple-50 px-2 py-1.5 dark:bg-purple-950/30">
                                <p class="text-[10px] uppercase text-purple-600 dark:text-purple-400">Sem dimensão</p>
                                <p class="text-lg font-bold text-purple-700 dark:text-purple-300">{{ storedReport.rejeitados_sem_dimensao }}</p>
                            </div>
                        </div>

                        <!-- Distribuição ABC — mini barras -->
                        <div v-if="abcStats.total > 0" class="mb-3 space-y-1.5">
                            <p class="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Curva ABC</p>
                            <div v-if="abcStats.a > 0" class="flex items-center gap-2">
                                <span class="w-4 shrink-0 text-[10px] font-bold text-emerald-600">A</span>
                                <div class="h-2 flex-1 overflow-hidden rounded-full bg-muted">
                                    <div class="h-full rounded-full bg-emerald-500 transition-all" :style="{ width: barWidth(abcStats.a, abcStats.total) }" />
                                </div>
                                <span class="w-5 shrink-0 text-right text-[10px] text-muted-foreground">{{ abcStats.a }}</span>
                            </div>
                            <div v-if="abcStats.b > 0" class="flex items-center gap-2">
                                <span class="w-4 shrink-0 text-[10px] font-bold text-yellow-600">B</span>
                                <div class="h-2 flex-1 overflow-hidden rounded-full bg-muted">
                                    <div class="h-full rounded-full bg-yellow-400 transition-all" :style="{ width: barWidth(abcStats.b, abcStats.total) }" />
                                </div>
                                <span class="w-5 shrink-0 text-right text-[10px] text-muted-foreground">{{ abcStats.b }}</span>
                            </div>
                            <div v-if="abcStats.c > 0" class="flex items-center gap-2">
                                <span class="w-4 shrink-0 text-[10px] font-bold text-orange-500">C</span>
                                <div class="h-2 flex-1 overflow-hidden rounded-full bg-muted">
                                    <div class="h-full rounded-full bg-orange-400 transition-all" :style="{ width: barWidth(abcStats.c, abcStats.total) }" />
                                </div>
                                <span class="w-5 shrink-0 text-right text-[10px] text-muted-foreground">{{ abcStats.c }}</span>
                            </div>
                            <div v-if="abcStats.sem > 0" class="flex items-center gap-2">
                                <span class="w-4 shrink-0 text-[10px] font-bold text-slate-400">—</span>
                                <div class="h-2 flex-1 overflow-hidden rounded-full bg-muted">
                                    <div class="h-full rounded-full bg-slate-300 transition-all dark:bg-slate-600" :style="{ width: barWidth(abcStats.sem, abcStats.total) }" />
                                </div>
                                <span class="w-5 shrink-0 text-right text-[10px] text-muted-foreground">{{ abcStats.sem }}</span>
                            </div>
                        </div>

                        <!-- Zonas térmicas -->
                        <div v-if="abcStats.total > 0 && (zoneStats.hot > 0 || zoneStats.cold > 0)" class="mb-3 space-y-1.5">
                            <p class="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Zonas Térmicas</p>
                            <div class="flex gap-3 text-xs">
                                <span v-if="zoneStats.hot > 0" class="flex items-center gap-1">
                                    <span class="inline-block h-2 w-2 rounded-full bg-orange-400" />
                                    <span class="text-muted-foreground">Quente</span>
                                    <span class="font-medium">{{ zoneStats.hot }}</span>
                                </span>
                                <span v-if="zoneStats.cold > 0" class="flex items-center gap-1">
                                    <span class="inline-block h-2 w-2 rounded-full bg-blue-400" />
                                    <span class="text-muted-foreground">Fria</span>
                                    <span class="font-medium">{{ zoneStats.cold }}</span>
                                </span>
                                <span v-if="zoneStats.neutral > 0" class="flex items-center gap-1">
                                    <span class="inline-block h-2 w-2 rounded-full bg-slate-300 dark:bg-slate-600" />
                                    <span class="text-muted-foreground">Neutra</span>
                                    <span class="font-medium">{{ zoneStats.neutral }}</span>
                                </span>
                            </div>
                        </div>

                        <!-- Score type -->
                        <p v-if="storedReport.score_type && storedReport.score_type !== 'neutral'" class="text-[10px] text-muted-foreground">
                            Score: <span class="font-medium capitalize">{{ storedReport.score_type }}</span>
                        </p>
                        <p v-else-if="storedReport.score_type === 'neutral'" class="text-[10px] text-blue-500">
                            Sem dados de venda no período — ordenação neutra
                        </p>
                    </div>
                </template>

                <!--
                <Separator />

                Redistribuir
                <div class="rounded-lg border border-border bg-background p-4 shadow-sm">
                    <div class="flex items-start gap-3">
                        <div class="mt-0.5 rounded-md bg-amber-500/10 p-2">
                            <LayoutGrid class="size-4 text-amber-600" />
                        </div>
                        <div class="flex-1">
                            <p class="text-sm font-medium">{{ t('plannerate.sidebar.generation.redistribute.title') }}</p>
                            <p class="mt-1 text-xs text-muted-foreground">
                                {{ t('plannerate.sidebar.generation.redistribute.description') }}
                            </p>
                            <Button variant="outline" size="sm" class="mt-3 w-full" :disabled="isRedistributing" @click="handleRedistribute" type="button">
                                <LayoutGrid v-if="!isRedistributing" class="mr-2 size-3.5" />
                                <span v-if="isRedistributing" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                {{ t('plannerate.sidebar.generation.redistribute.title') }}
                            </Button>
                        </div>
                    </div>
                </div>

                Reordenar
                <div class="rounded-lg border border-border bg-background p-4 shadow-sm">
                    <div class="flex items-start gap-3">
                        <div class="mt-0.5 rounded-md bg-blue-500/10 p-2">
                            <ArrowUpDown class="size-4 text-blue-600" />
                        </div>
                        <div class="flex-1">
                            <p class="text-sm font-medium">{{ t('plannerate.sidebar.generation.reorder.title') }}</p>
                            <p class="mt-1 text-xs text-muted-foreground">
                                {{ t('plannerate.sidebar.generation.reorder.description') }}
                            </p>
                            <Button variant="outline" size="sm" class="mt-3 w-full" :disabled="isReordering" @click="handleReorder" type="button">
                                <ArrowUpDown v-if="!isReordering" class="mr-2 size-3.5" />
                                <span v-if="isReordering" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                {{ t('plannerate.sidebar.generation.reorder.title') }}
                            </Button>
                        </div>
                    </div>
                </div>
                -->
            </div>
        </div>
    </Transition>
</template>
