<script setup lang="ts">
import { router } from '@inertiajs/vue3';
import axios from 'axios';
import { ArrowUpDown, LayoutGrid, RefreshCw, Sparkles, X } from 'lucide-vue-next';
import { computed, ref } from 'vue';
import { toast } from 'vue-sonner';
import { reorderGondola, redistributeGondola, regenerateAuto } from '@/actions/App/Http/Controllers/AutoPlanogramController';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { useT } from '@/composables/useT';
import type { Gondola } from '../../../types/planogram';
import CategoryConfigPanel from './CategoryConfigPanel.vue';

interface Props {
    open: boolean;
    gondola: Gondola;
}

interface Emits {
    (e: 'close'): void;
    (e: 'reload'): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();
const { t } = useT();

const modeLabel: Record<string, string> = {
    template: 'Template',
    automatic: 'Automático',
    manual: 'Manual',
};

const modeVariant: Record<string, 'default' | 'secondary' | 'outline'> = {
    template: 'default',
    automatic: 'secondary',
    manual: 'outline',
};

const currentMode = props.gondola.generation_mode ?? 'manual';
const isReordering = ref(false);
const isRedistributing = ref(false);
const isPromoting = ref(false);
const isRegeneratingAuto = ref(false);

/** True quando o template vinculado à gôndola foi gerado pelo modo automático */
const isAutoGeneratedTemplate = computed(
    () => props.gondola.template_origin === 'auto',
);

/** URL de promoção do template: POST /planogram-templates/{id}/promote */
function promoteUrl(templateId: string): string {
    return `/planogram-templates/${templateId}/promote`;
}

async function handleReorder() {
    isReordering.value = true;
    try {
        await axios.post(reorderGondola.url(props.gondola.id));
        toast.success(t('plannerate.sidebar.generation.reorder.success'));
        router.reload({ only: ['record'] });
    } catch {
        toast.error(t('plannerate.sidebar.generation.reorder.error'));
    } finally {
        isReordering.value = false;
    }
}

async function handleRedistribute() {
    isRedistributing.value = true;
    try {
        await axios.post(redistributeGondola.url(props.gondola.id));
        toast.success(t('plannerate.sidebar.generation.redistribute.success'));
        router.reload({ only: ['record'] });
    } catch {
        toast.error(t('plannerate.sidebar.generation.redistribute.error'));
    } finally {
        isRedistributing.value = false;
    }
}

async function handlePromote() {
    if (!props.gondola.template_id) {
        return;
    }
    isPromoting.value = true;
    try {
        await axios.post(promoteUrl(props.gondola.template_id));
        toast.success(t('plannerate.sidebar.generation.auto_generated.promote_success'));
        router.reload({ only: ['record'] });
    } catch {
        toast.error(t('plannerate.sidebar.generation.auto_generated.promote_error'));
    } finally {
        isPromoting.value = false;
    }
}

async function handleRegenerateAuto() {
    isRegeneratingAuto.value = true;
    try {
        await axios.post(regenerateAuto.url(props.gondola.id));
        toast.success(t('plannerate.sidebar.generation.auto_generated.regenerate_auto_success'));
        router.reload({ only: ['record'] });
    } catch {
        toast.error(t('plannerate.sidebar.generation.auto_generated.regenerate_auto_error'));
    } finally {
        isRegeneratingAuto.value = false;
    }
}
</script>

<template>
    <Transition
        enter-active-class="transition-transform duration-300 ease-out"
        enter-from-class="-translate-x-full"
        enter-to-class="translate-x-0"
        leave-active-class="transition-transform duration-300 ease-in"
        leave-from-class="translate-x-0"
        leave-to-class="-translate-x-full"
    >
        <div
            v-if="open"
            class="relative z-20 flex h-full w-full sm:w-80 2xl:w-96 flex-col border-r border-border bg-background"
        >
            <!-- Header -->
            <div class="flex items-center justify-between border-b border-border px-4 py-3">
                <div class="flex items-center gap-2">
                    <span class="text-sm font-medium">{{ t('plannerate.sidebar.generation.title') }}</span>
                    <Badge :variant="modeVariant[currentMode] ?? 'outline'">
                        {{ modeLabel[currentMode] ?? currentMode }}
                    </Badge>
                </div>
                <Button variant="ghost" size="icon" class="size-7 shrink-0" @click="$emit('close')" type="button">
                    <X class="size-4" />
                </Button>
            </div>

            <!-- Template info -->
            <div v-if="gondola.template_id" class="border-b border-border bg-muted/30 px-4 py-2">
                <p class="text-xs text-muted-foreground">{{ t('plannerate.sidebar.generation.template_in_use') }}</p>
                <p class="mt-0.5 text-xs font-medium text-foreground">{{ gondola.template_id }}</p>
            </div>

            <!-- Content -->
            <div class="flex flex-1 flex-col gap-3 overflow-y-auto p-4">

                <!-- Card: Template gerado automaticamente -->
                <div
                    v-if="isAutoGeneratedTemplate && gondola.template_id"
                    class="rounded-lg border border-violet-200 bg-violet-50 p-4 shadow-sm dark:border-violet-800 dark:bg-violet-950"
                >
                    <div class="flex items-start gap-3">
                        <div class="mt-0.5 rounded-md bg-violet-500/10 p-2">
                            <Sparkles class="size-4 text-violet-600 dark:text-violet-400" />
                        </div>
                        <div class="flex-1">
                            <p class="text-sm font-medium text-violet-900 dark:text-violet-100">
                                {{ t('plannerate.sidebar.generation.auto_generated.title') }}
                            </p>
                            <p class="mt-1 text-xs text-violet-700 dark:text-violet-300">
                                {{ t('plannerate.sidebar.generation.auto_generated.description') }}
                            </p>
                            <div class="mt-3 flex flex-col gap-2">
                                <Button
                                    variant="default"
                                    size="sm"
                                    class="w-full bg-violet-600 hover:bg-violet-700 text-white"
                                    :disabled="isPromoting"
                                    @click="handlePromote"
                                    type="button"
                                >
                                    <span v-if="isPromoting" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                    <Sparkles v-else class="mr-2 size-3.5" />
                                    {{ t('plannerate.sidebar.generation.auto_generated.promote') }}
                                </Button>
                                <Button
                                    variant="outline"
                                    size="sm"
                                    class="w-full"
                                    :disabled="isRegeneratingAuto"
                                    @click="handleRegenerateAuto"
                                    type="button"
                                >
                                    <span v-if="isRegeneratingAuto" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                    <RefreshCw v-else class="mr-2 size-3.5" />
                                    {{ t('plannerate.sidebar.generation.auto_generated.regenerate_auto') }}
                                </Button>
                            </div>
                        </div>
                    </div>
                </div>

                <Separator v-if="isAutoGeneratedTemplate && gondola.template_id" />

                <!-- Configurações por categoria -->
                <CategoryConfigPanel :gondola="gondola" />

                <!--
                <Separator />

                Redistribuir
                <div class="rounded-lg border border-border bg-background p-4 shadow-sm">
                    <div class="flex items-start gap-3">
                        <div class="mt-0.5 rounded-md bg-amber-500/10 p-2">
                            <LayoutGrid class="size-4 text-amber-600" />
                        </div>
                        <div class="flex-1">
                            <p class="text-sm font-medium">{{ t('plannerate.sidebar.generation.redistribute.title') }}</p>
                            <p class="mt-1 text-xs text-muted-foreground">
                                {{ t('plannerate.sidebar.generation.redistribute.description') }}
                            </p>
                            <Button variant="outline" size="sm" class="mt-3 w-full" :disabled="isRedistributing" @click="handleRedistribute" type="button">
                                <LayoutGrid v-if="!isRedistributing" class="mr-2 size-3.5" />
                                <span v-if="isRedistributing" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                {{ t('plannerate.sidebar.generation.redistribute.title') }}
                            </Button>
                        </div>
                    </div>
                </div>

                Reordenar
                <div class="rounded-lg border border-border bg-background p-4 shadow-sm">
                    <div class="flex items-start gap-3">
                        <div class="mt-0.5 rounded-md bg-blue-500/10 p-2">
                            <ArrowUpDown class="size-4 text-blue-600" />
                        </div>
                        <div class="flex-1">
                            <p class="text-sm font-medium">{{ t('plannerate.sidebar.generation.reorder.title') }}</p>
                            <p class="mt-1 text-xs text-muted-foreground">
                                {{ t('plannerate.sidebar.generation.reorder.description') }}
                            </p>
                            <Button variant="outline" size="sm" class="mt-3 w-full" :disabled="isReordering" @click="handleReorder" type="button">
                                <ArrowUpDown v-if="!isReordering" class="mr-2 size-3.5" />
                                <span v-if="isReordering" class="mr-2 size-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />
                                {{ t('plannerate.sidebar.generation.reorder.title') }}
                            </Button>
                        </div>
                    </div>
                </div>
                -->
            </div>
        </div>
    </Transition>
</template>
